# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice-JH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice-JH
  pod 'KakaoSDKUser' # 카카오 로그인
  pod 'KakaoSDKCommon' # 카카오 일반
  pod 'JJFloatingActionButton' # 플로팅버튼
  pod 'KakaoSDKAuth' # 사용자 관리
  pod 'SnapKit', '~> 5.0.0'

end
