# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice-JH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice-JH
  pod 'KakaoSDKUser' # 카카오 로그인
  pod 'KakaoSDKUser' # 사용자 관리

end
